baseURL = "https://docs.kamui-code.ai/"
languageCode = "ja"
title = "KAMUI CODE MCP Docs"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  siteName = "KAMUI CODE"
  siteSubtitle = "MCP Docs"
